// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { Award, Shield, Sparkles } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutFeaturesSplit
          tag="Quiénes somos"
          title="Excelencia en Estética"
          description="Nuestra estética se enfoca en ofrecer una experiencia premium con técnicas innovadoras y un trato cercano."
          items={[
            {
              icon: Sparkles,
              title: "Tratamientos Premium",
              description: "Soluciones personalizadas para cada tipo de piel.",
            },
            {
              icon: Shield,
              title: "Seguridad Total",
              description: "Productos de alta gama y protocolos certificados.",
            },
            {
              icon: Award,
              title: "Expertos Certificados",
              description: "Personal altamente capacitado para tu cuidado.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/relaxed-woman-receiving-facial-massage-with-herbal-balls-spa-treatment-beauty-salon_637285-2177.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
