// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Contacto"
          text="¿Lista para comenzar tu transformación?"
          primaryButton={{
            text: "WhatsApp",
            href: "https://wa.me/1234567890",
          }}
          secondaryButton={{
            text: "Email",
            href: "mailto:info@esteticaluxe.com",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
