// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardCarousel from '@/components/sections/hero/HeroBillboardCarousel';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboardCarousel
          tag=""
          title="Belleza y Bienestar en Armonía"
          description="Descubre nuestros tratamientos estéticos exclusivos diseñados para resaltar tu belleza natural con la máxima serenidad."
          primaryButton={{
            text: "Reservar Cita",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Ver Servicios",
            href: "#servicios",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/black-white-nude-woman-full-shot_23-2149428721.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-flowers-mirror_23-2148879007.jpg",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3H9qby8SalGK2F1HraxFX3CLIXR/uploaded-1785294543437-pbtt09iu.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/mirror-vases-background-zoom-calls_23-2149684461.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/elements-relaxing-massage-spa_23-2148176934.jpg",
            },
            {
              imageSrc: "https://storage.googleapis.com/webild/users/user_3H9qby8SalGK2F1HraxFX3CLIXR/uploaded-1785294264785-pdruytti.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
