// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsMediaCards
          tag="Resultados comprobados"
          title="Nuestros logros en cifras"
          description="La confianza de nuestros clientes nos impulsa a seguir mejorando."
          metrics={[
            {
              value: "1500+",
              title: "Clientes satisfechos",
              description: "Personas que han confiado en nuestro cuidado.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-smiling-confident-young-chambermaid-hotel-room_23-2148033192.jpg",
            },
            {
              value: "98%",
              title: "Resultados visibles",
              description: "Porcentaje de clientes satisfechos con su cambio.",
              imageSrc: "http://img.b2bpic.net/free-photo/girl-looking-her-reflection_23-2148147523.jpg",
            },
            {
              value: "10+",
              title: "Certificaciones",
              description: "Avalan nuestra experiencia y técnica.",
              imageSrc: "http://img.b2bpic.net/free-photo/gorgeous-smiling-blonde-fashion-model-sits-white-suit-soft-armchair_8353-5476.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
