// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingLayeredCards from '@/components/sections/pricing/PricingLayeredCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
        <SectionErrorBoundary name="pricing">
              <PricingLayeredCards
          tag="Inversión en ti"
          title="Planes de Belleza"
          description="Elige la experiencia que mejor se adapte a tus necesidades."
          plans={[
            {
              tag: "Básico",
              price: "$45",
              description: "Limpieza facial profunda y masaje.",
              primaryButton: {
                text: "Elegir",
                href: "#contact",
              },
              features: [
                "Limpieza",
                "Hidratación",
                "Masaje",
              ],
            },
            {
              tag: "Premium",
              price: "$90",
              description: "Tratamiento completo con aparatología.",
              primaryButton: {
                text: "Elegir",
                href: "#contact",
              },
              features: [
                "Todo lo básico",
                "Aparatología",
                "Contorno ojos",
              ],
            },
            {
              tag: "Elite",
              price: "$150",
              description: "Experiencia completa de lujo.",
              primaryButton: {
                text: "Elegir",
                href: "#contact",
              },
              features: [
                "Todo lo premium",
                "Peeling Químico",
                "Regalo sorpresa",
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
