// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "productos" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductosSection(): React.JSX.Element {
  return (
    <div id="productos" data-section="productos">
        <SectionErrorBoundary name="productos">
              <FeaturesImageBento
          tag="Nuestra Línea"
          title="Productos de Alta Calidad"
          description="Solo utilizamos lo mejor para tu piel."
          items={[
            {
              title: "Sueros Premium",
              description: "Hidratación profunda.",
              imageSrc: "http://img.b2bpic.net/free-photo/beauty-cosmetics-product-with-soft-pink-tones_23-2151005504.jpg",
            },
            {
              title: "Mascarillas",
              description: "Rejuvenecimiento intenso.",
              imageSrc: "http://img.b2bpic.net/free-photo/monochrome-beauty-product-skincare_23-2151307294.jpg",
            },
            {
              title: "Aceites",
              description: "Nutrición natural.",
              imageSrc: "http://img.b2bpic.net/free-photo/front-view-organic-body-care-serum_23-2148317629.jpg",
            },
            {
              title: "Jabones",
              description: "Limpieza suave.",
              imageSrc: "http://img.b2bpic.net/free-photo/arrangement-with-flowers-white-background_23-2148345624.jpg",
            },
            {
              title: "Cremas",
              description: "Protección diaria.",
              imageSrc: "http://img.b2bpic.net/free-photo/cosmetics-product-with-balloons_187299-46268.jpg",
            },
            {
              title: "Esencias",
              description: "Claridad y brillo.",
              imageSrc: "http://img.b2bpic.net/free-photo/still-life-with-razor-blade_23-2151102218.jpg",
            },
            {
              title: "Piedras Spa",
              description: "Relajación total.",
              imageSrc: "http://img.b2bpic.net/free-photo/full-shot-people-relaxing-indoors_23-2151030602.jpg",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
