// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "servicios" section.

import React from 'react';
import FeaturesDetailedSteps from '@/components/sections/features/FeaturesDetailedSteps';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServiciosSection(): React.JSX.Element {
  return (
    <div id="servicios" data-section="servicios">
        <SectionErrorBoundary name="servicios">
              <FeaturesDetailedSteps
          tag="Nuestra Metodología"
          title="cm"
          description="Seguimos un proceso cuidadoso para asegurar resultados visibles y duraderos."
          steps={[
            {
              tag: "Paso 1",
              title: "Diagnóstico",
              subtitle: "Evaluación gratuita",
              description: "Analizamos tu piel para personalizar tu tratamiento.",
              imageSrc: "http://img.b2bpic.net/free-photo/spa-composition-with-thai-orchid-flowers-bath-accessories_169016-17218.jpg",
            },
            {
              tag: "Paso 2",
              title: "Tratamiento",
              subtitle: "Tecnología avanzada",
              description: "Aplicamos los métodos más eficaces con cuidado.",
              imageSrc: "http://img.b2bpic.net/free-photo/spa-composition-objects_169016-6411.jpg",
            },
            {
              tag: "Paso 3",
              title: "Seguimiento",
              subtitle: "Cuidado continuo",
              description: "Te asesoramos para mantener los resultados en casa.",
              imageSrc: "http://img.b2bpic.net/free-photo/spa-soap-with-wooden-hairbrush_23-2147844987.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
