// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
          tag="Experiencias"
          title="Lo que dicen nuestras clientas"
          description="Tu satisfacción es nuestro mayor éxito."
          testimonials={[
            {
              name: "Ana García",
              role: "Clienta frecuente",
              quote: "Increíble trato, mi piel ha mejorado notablemente.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-blonde-short-haired-woman-posing-white-shirt_23-2149021781.jpg",
            },
            {
              name: "Laura Méndez",
              role: "Primera visita",
              quote: "La mejor experiencia de spa que he tenido jamás.",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-plus-sized-woman-influencer_23-2151414125.jpg",
            },
            {
              name: "Sofía Ruiz",
              role: "Clienta",
              quote: "Un lugar lleno de paz y profesionales expertos.",
              imageSrc: "http://img.b2bpic.net/free-photo/happy-beautiful-girl-is-happy-smiling-laughing-look-stright-expressive-facial-expressions-cosmet_1258-143998.jpg",
            },
            {
              name: "Elena Torres",
              role: "Clienta frecuente",
              quote: "Excelente servicio, los resultados son inmediatos.",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-taking-care-herself_23-2148976931.jpg",
            },
            {
              name: "Lucía Rey",
              role: "Clienta",
              quote: "Totalmente recomendado, volveré muy pronto seguro.",
              imageSrc: "http://img.b2bpic.net/free-photo/bride-getting-hair-done-side-view_23-2149860771.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
